/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BetiPredictMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "MIN_LIQUIDITY"
      | "SCALE"
      | "buyNo"
      | "buyYes"
      | "cancelMarket"
      | "claimRefund"
      | "claimWinnings"
      | "claimed"
      | "collateralDecimals"
      | "collateralToken"
      | "createMarket"
      | "creationFee"
      | "estimateBuy"
      | "estimateSell"
      | "getMarket"
      | "getNoPrice"
      | "getPosition"
      | "getYesPrice"
      | "marketCount"
      | "markets"
      | "noShares"
      | "owner"
      | "pause"
      | "paused"
      | "platformBalance"
      | "renounceOwnership"
      | "resolveMarket"
      | "resolvers"
      | "sellNo"
      | "sellYes"
      | "setCreationFee"
      | "setResolver"
      | "setTradingFee"
      | "tradingFee"
      | "transferOwnership"
      | "unpause"
      | "withdrawFees"
      | "yesShares"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesWithdrawn"
      | "MarketCancelled"
      | "MarketCreated"
      | "MarketResolved"
      | "OwnershipTransferred"
      | "Paused"
      | "RefundClaimed"
      | "ResolverUpdated"
      | "SharesPurchased"
      | "SharesSold"
      | "TradingFeeUpdated"
      | "Unpaused"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SCALE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyNo",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyYes",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "estimateBuy",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateSell",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNoPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYesPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "noShares",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellNo",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellYes",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setResolver",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tradingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "yesShares",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SCALE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyNo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyYes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNoPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYesPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolvers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellNo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellYes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tradingFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yesShares", data: BytesLike): Result;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [marketId: BigNumberish, canceller: AddressLike];
  export type OutputTuple = [marketId: bigint, canceller: string];
  export interface OutputObject {
    marketId: bigint;
    canceller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    question: string,
    resolveTime: BigNumberish,
    creator: AddressLike,
    initialLiquidity: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    question: string,
    resolveTime: bigint,
    creator: string,
    initialLiquidity: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    question: string;
    resolveTime: bigint;
    creator: string;
    initialLiquidity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    resolution: BigNumberish,
    resolver: AddressLike
  ];
  export type OutputTuple = [
    marketId: bigint,
    resolution: bigint,
    resolver: string
  ];
  export interface OutputObject {
    marketId: bigint;
    resolution: bigint;
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    refund: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, user: string, refund: bigint];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    refund: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverUpdatedEvent {
  export type InputTuple = [resolver: AddressLike, authorized: boolean];
  export type OutputTuple = [resolver: string, authorized: boolean];
  export interface OutputObject {
    resolver: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesPurchasedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    buyer: AddressLike,
    outcome: BigNumberish,
    collateralIn: BigNumberish,
    sharesOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    buyer: string,
    outcome: bigint,
    collateralIn: bigint,
    sharesOut: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    buyer: string;
    outcome: bigint;
    collateralIn: bigint;
    sharesOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesSoldEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    seller: AddressLike,
    outcome: BigNumberish,
    sharesIn: BigNumberish,
    collateralOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    seller: string,
    outcome: bigint,
    sharesIn: bigint,
    collateralOut: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    seller: string;
    outcome: bigint;
    sharesIn: bigint;
    collateralOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradingFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    payout: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, user: string, payout: bigint];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BetiPredictMarket extends BaseContract {
  connect(runner?: ContractRunner | null): BetiPredictMarket;
  waitForDeployment(): Promise<this>;

  interface: BetiPredictMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MIN_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  SCALE: TypedContractMethod<[], [bigint], "view">;

  buyNo: TypedContractMethod<
    [_marketId: BigNumberish, _amount: BigNumberish, _minShares: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  buyYes: TypedContractMethod<
    [_marketId: BigNumberish, _amount: BigNumberish, _minShares: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  cancelMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimWinnings: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  collateralDecimals: TypedContractMethod<[], [bigint], "view">;

  collateralToken: TypedContractMethod<[], [string], "view">;

  createMarket: TypedContractMethod<
    [
      _question: string,
      _resolveTime: BigNumberish,
      _initialLiquidity: BigNumberish,
      _resolver: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  creationFee: TypedContractMethod<[], [bigint], "view">;

  estimateBuy: TypedContractMethod<
    [_marketId: BigNumberish, _outcome: BigNumberish, _amount: BigNumberish],
    [[bigint, bigint] & { sharesOut: bigint; fee: bigint }],
    "view"
  >;

  estimateSell: TypedContractMethod<
    [_marketId: BigNumberish, _outcome: BigNumberish, _shares: BigNumberish],
    [[bigint, bigint] & { collateralOut: bigint; fee: bigint }],
    "view"
  >;

  getMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        question: string;
        resolveTime: bigint;
        yesPool: bigint;
        noPool: bigint;
        totalVolume: bigint;
        status: bigint;
        resolution: bigint;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getNoPrice: TypedContractMethod<[_marketId: BigNumberish], [bigint], "view">;

  getPosition: TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        yesAmount: bigint;
        noAmount: bigint;
        hasClaimed: boolean;
      }
    ],
    "view"
  >;

  getYesPrice: TypedContractMethod<[_marketId: BigNumberish], [bigint], "view">;

  marketCount: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint
      ] & {
        id: bigint;
        question: string;
        resolveTime: bigint;
        yesPool: bigint;
        noPool: bigint;
        totalVolume: bigint;
        status: bigint;
        resolution: bigint;
        creator: string;
        resolver: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  noShares: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformBalance: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveMarket: TypedContractMethod<
    [_marketId: BigNumberish, _resolution: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolvers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  sellNo: TypedContractMethod<
    [
      _marketId: BigNumberish,
      _shares: BigNumberish,
      _minCollateral: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  sellYes: TypedContractMethod<
    [
      _marketId: BigNumberish,
      _shares: BigNumberish,
      _minCollateral: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  setCreationFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setResolver: TypedContractMethod<
    [_resolver: AddressLike, _authorized: boolean],
    [void],
    "nonpayable"
  >;

  setTradingFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  tradingFee: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawFees: TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  yesShares: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCALE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyNo"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _amount: BigNumberish, _minShares: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyYes"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _amount: BigNumberish, _minShares: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "collateralDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "collateralToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      _question: string,
      _resolveTime: BigNumberish,
      _initialLiquidity: BigNumberish,
      _resolver: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "estimateBuy"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _outcome: BigNumberish, _amount: BigNumberish],
    [[bigint, bigint] & { sharesOut: bigint; fee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "estimateSell"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _outcome: BigNumberish, _shares: BigNumberish],
    [[bigint, bigint] & { collateralOut: bigint; fee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        question: string;
        resolveTime: bigint;
        yesPool: bigint;
        noPool: bigint;
        totalVolume: bigint;
        status: bigint;
        resolution: bigint;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNoPrice"
  ): TypedContractMethod<[_marketId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        yesAmount: bigint;
        noAmount: bigint;
        hasClaimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYesPrice"
  ): TypedContractMethod<[_marketId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint
      ] & {
        id: bigint;
        question: string;
        resolveTime: bigint;
        yesPool: bigint;
        noPool: bigint;
        totalVolume: bigint;
        status: bigint;
        resolution: bigint;
        creator: string;
        resolver: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "noShares"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _resolution: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolvers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sellNo"
  ): TypedContractMethod<
    [
      _marketId: BigNumberish,
      _shares: BigNumberish,
      _minCollateral: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellYes"
  ): TypedContractMethod<
    [
      _marketId: BigNumberish,
      _shares: BigNumberish,
      _minCollateral: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCreationFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setResolver"
  ): TypedContractMethod<
    [_resolver: AddressLike, _authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTradingFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tradingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yesShares"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverUpdated"
  ): TypedContractEvent<
    ResolverUpdatedEvent.InputTuple,
    ResolverUpdatedEvent.OutputTuple,
    ResolverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SharesPurchased"
  ): TypedContractEvent<
    SharesPurchasedEvent.InputTuple,
    SharesPurchasedEvent.OutputTuple,
    SharesPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "SharesSold"
  ): TypedContractEvent<
    SharesSoldEvent.InputTuple,
    SharesSoldEvent.OutputTuple,
    SharesSoldEvent.OutputObject
  >;
  getEvent(
    key: "TradingFeeUpdated"
  ): TypedContractEvent<
    TradingFeeUpdatedEvent.InputTuple,
    TradingFeeUpdatedEvent.OutputTuple,
    TradingFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "MarketCancelled(uint256,address)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketCreated(uint256,string,uint256,address,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint8,address)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RefundClaimed(uint256,address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "ResolverUpdated(address,bool)": TypedContractEvent<
      ResolverUpdatedEvent.InputTuple,
      ResolverUpdatedEvent.OutputTuple,
      ResolverUpdatedEvent.OutputObject
    >;
    ResolverUpdated: TypedContractEvent<
      ResolverUpdatedEvent.InputTuple,
      ResolverUpdatedEvent.OutputTuple,
      ResolverUpdatedEvent.OutputObject
    >;

    "SharesPurchased(uint256,address,uint8,uint256,uint256,uint256)": TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;
    SharesPurchased: TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;

    "SharesSold(uint256,address,uint8,uint256,uint256,uint256)": TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;
    SharesSold: TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;

    "TradingFeeUpdated(uint256,uint256)": TypedContractEvent<
      TradingFeeUpdatedEvent.InputTuple,
      TradingFeeUpdatedEvent.OutputTuple,
      TradingFeeUpdatedEvent.OutputObject
    >;
    TradingFeeUpdated: TypedContractEvent<
      TradingFeeUpdatedEvent.InputTuple,
      TradingFeeUpdatedEvent.OutputTuple,
      TradingFeeUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WinningsClaimed(uint256,address,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
