/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BetiPredictMarket } from "./BetiPredictMarket";
export type { BetiPredictSimple } from "./BetiPredictSimple";
export type { MockToken } from "./MockToken";
