/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BetiPredictSimple {
  export type MarketStruct = {
    id: BigNumberish;
    title: string;
    description: string;
    category: string;
    question: string;
    resolveTime: BigNumberish;
    yesPrice: BigNumberish;
    noPrice: BigNumberish;
    totalVolume: BigNumberish;
    status: BigNumberish;
    resolution: BigNumberish;
    creator: AddressLike;
    createdAt: BigNumberish;
  };

  export type MarketStructOutput = [
    id: bigint,
    title: string,
    description: string,
    category: string,
    question: string,
    resolveTime: bigint,
    yesPrice: bigint,
    noPrice: bigint,
    totalVolume: bigint,
    status: bigint,
    resolution: bigint,
    creator: string,
    createdAt: bigint
  ] & {
    id: bigint;
    title: string;
    description: string;
    category: string;
    question: string;
    resolveTime: bigint;
    yesPrice: bigint;
    noPrice: bigint;
    totalVolume: bigint;
    status: bigint;
    resolution: bigint;
    creator: string;
    createdAt: bigint;
  };

  export type OrderStruct = {
    id: BigNumberish;
    marketId: BigNumberish;
    trader: AddressLike;
    side: BigNumberish;
    orderType: BigNumberish;
    outcome: BigNumberish;
    amount: BigNumberish;
    price: BigNumberish;
    filled: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
  };

  export type OrderStructOutput = [
    id: bigint,
    marketId: bigint,
    trader: string,
    side: bigint,
    orderType: bigint,
    outcome: bigint,
    amount: bigint,
    price: bigint,
    filled: bigint,
    status: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    marketId: bigint;
    trader: string;
    side: bigint;
    orderType: bigint;
    outcome: bigint;
    amount: bigint;
    price: bigint;
    filled: bigint;
    status: bigint;
    createdAt: bigint;
  };
}

export interface BetiPredictSimpleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "collateralToken"
      | "createMarket"
      | "deposit"
      | "getBalance"
      | "getMarket"
      | "getOrder"
      | "getUserOrders"
      | "marketCounter"
      | "marketCreationFee"
      | "markets"
      | "orderCounter"
      | "orders"
      | "owner"
      | "pause"
      | "paused"
      | "placeLimitOrder"
      | "placeMarketOrder"
      | "renounceOwnership"
      | "resolveMarket"
      | "setMarketCreationFee"
      | "transferOwnership"
      | "unpause"
      | "userBalances"
      | "userOrders"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCreated"
      | "MarketResolved"
      | "OrderFilled"
      | "OrderPlaced"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketCreationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orderCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeLimitOrder",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "placeMarketOrder",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketCreationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orderCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "placeLimitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeMarketOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userOrders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    title: string,
    question: string,
    resolveTime: BigNumberish,
    creator: AddressLike
  ];
  export type OutputTuple = [
    marketId: bigint,
    title: string,
    question: string,
    resolveTime: bigint,
    creator: string
  ];
  export interface OutputObject {
    marketId: bigint;
    title: string;
    question: string;
    resolveTime: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    resolution: BigNumberish,
    totalPayout: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    resolution: bigint,
    totalPayout: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    resolution: bigint;
    totalPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    marketId: BigNumberish,
    trader: AddressLike,
    filledAmount: BigNumberish,
    fillPrice: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    marketId: bigint,
    trader: string,
    filledAmount: bigint,
    fillPrice: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    marketId: bigint;
    trader: string;
    filledAmount: bigint;
    fillPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderPlacedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    marketId: BigNumberish,
    trader: AddressLike,
    side: BigNumberish,
    outcome: BigNumberish,
    amount: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    marketId: bigint,
    trader: string,
    side: bigint,
    outcome: bigint,
    amount: bigint,
    price: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    marketId: bigint;
    trader: string;
    side: bigint;
    outcome: bigint;
    amount: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BetiPredictSimple extends BaseContract {
  connect(runner?: ContractRunner | null): BetiPredictSimple;
  waitForDeployment(): Promise<this>;

  interface: BetiPredictSimpleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  collateralToken: TypedContractMethod<[], [string], "view">;

  createMarket: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _category: string,
      _question: string,
      _resolveTime: BigNumberish,
      _initialYesPrice: BigNumberish,
      _initialNoPrice: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  deposit: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getBalance: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  getMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [BetiPredictSimple.MarketStructOutput],
    "view"
  >;

  getOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [BetiPredictSimple.OrderStructOutput],
    "view"
  >;

  getUserOrders: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  marketCounter: TypedContractMethod<[], [bigint], "view">;

  marketCreationFee: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        title: string;
        description: string;
        category: string;
        question: string;
        resolveTime: bigint;
        yesPrice: bigint;
        noPrice: bigint;
        totalVolume: bigint;
        status: bigint;
        resolution: bigint;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  orderCounter: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        marketId: bigint;
        trader: string;
        side: bigint;
        orderType: bigint;
        outcome: bigint;
        amount: bigint;
        price: bigint;
        filled: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  placeLimitOrder: TypedContractMethod<
    [
      _marketId: BigNumberish,
      _side: BigNumberish,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  placeMarketOrder: TypedContractMethod<
    [
      _marketId: BigNumberish,
      _side: BigNumberish,
      _outcome: BigNumberish,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveMarket: TypedContractMethod<
    [_marketId: BigNumberish, _resolution: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMarketCreationFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "collateralToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _category: string,
      _question: string,
      _resolveTime: BigNumberish,
      _initialYesPrice: BigNumberish,
      _initialNoPrice: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish],
    [BetiPredictSimple.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [_orderId: BigNumberish],
    [BetiPredictSimple.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "marketCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketCreationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        title: string;
        description: string;
        category: string;
        question: string;
        resolveTime: bigint;
        yesPrice: bigint;
        noPrice: bigint;
        totalVolume: bigint;
        status: bigint;
        resolution: bigint;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "orderCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        marketId: bigint;
        trader: string;
        side: bigint;
        orderType: bigint;
        outcome: bigint;
        amount: bigint;
        price: bigint;
        filled: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "placeLimitOrder"
  ): TypedContractMethod<
    [
      _marketId: BigNumberish,
      _side: BigNumberish,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "placeMarketOrder"
  ): TypedContractMethod<
    [
      _marketId: BigNumberish,
      _side: BigNumberish,
      _outcome: BigNumberish,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish, _resolution: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMarketCreationFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "OrderPlaced"
  ): TypedContractEvent<
    OrderPlacedEvent.InputTuple,
    OrderPlacedEvent.OutputTuple,
    OrderPlacedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "MarketCreated(uint256,string,string,uint256,address)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint8,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "OrderFilled(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "OrderPlaced(uint256,uint256,address,uint8,uint8,uint256,uint256)": TypedContractEvent<
      OrderPlacedEvent.InputTuple,
      OrderPlacedEvent.OutputTuple,
      OrderPlacedEvent.OutputObject
    >;
    OrderPlaced: TypedContractEvent<
      OrderPlacedEvent.InputTuple,
      OrderPlacedEvent.OutputTuple,
      OrderPlacedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
