/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BetiPredictMarket__factory } from "./BetiPredictMarket__factory";
export { BetiPredictSimple__factory } from "./BetiPredictSimple__factory";
export { MockToken__factory } from "./MockToken__factory";
